[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.19"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/"
  to = "/cv.html"
  status = 200
